version: '3.8'

services:
  fastfood-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fastfood
      - SPRING_DATASOURCE_USERNAME=fastfood
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres
    networks:
      - fastfood-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fastfood
      - POSTGRES_USER=fastfood
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood-network

volumes:
  postgres_data:

networks:
  fastfood-network:
    driver: bridge

