apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastfood

resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/secret.yaml
- ../../base/postgres.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/hpa.yaml
- ../../base/vpa.yaml
- ../../base/ingress.yaml
- ../../base/monitoring.yaml

patchesStrategicMerge:
- deployment-prod.yaml

images:
- name: fastfood-api
  newTag: latest

replicas:
- name: fastfood-api
  count: 3

configMapGenerator:
- name: fastfood-config-prod
  literals:
  - SPRING_PROFILES_ACTIVE=prod
  - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/fastfood
  - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
  - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
  - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  - SPRING_JPA_SHOW_SQL=false
  - MERCADOPAGO_ENABLED=true

secretGenerator:
- name: fastfood-secrets-prod
  literals:
  - SPRING_DATASOURCE_USERNAME=fastfood
  - SPRING_DATASOURCE_PASSWORD=fastfood123
  - POSTGRES_USER=fastfood
  - POSTGRES_PASSWORD=fastfood123
  - POSTGRES_DB=fastfood
  - MERCADOPAGO_ACCESS_TOKEN=YOUR_MERCADO_PAGO_ACCESS_TOKEN
  - JWT_SECRET=your_super_secret_jwt_key_for_production

commonLabels:
  environment: production
  version: v1.0.0

commonAnnotations:
  environment: production

