apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fastfood-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- vpa.yaml
- pdb.yaml
- ingress.yaml
- monitoring.yaml

commonLabels:
  app: fastfood-api
  version: v1.0.0

images:
- name: fastfood-api
  newTag: latest

replicas:
- name: fastfood-api
  count: 3

