apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastfood-dev

resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/secret.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/hpa.yaml
- ../../base/ingress.yaml

patchesStrategicMerge:
- deployment-dev.yaml
- service-dev.yaml

images:
- name: fastfood-api
  newTag: dev

replicas:
- name: fastfood-api
  count: 1

configMapGenerator:
- name: fastfood-config-dev
  literals:
  - SPRING_PROFILES_ACTIVE=dev
  - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
  - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
  - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
  - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  - SPRING_JPA_SHOW_SQL=true
  - SPRING_H2_CONSOLE_ENABLED=true

secretGenerator:
- name: fastfood-secrets-dev
  literals:
  - SPRING_DATASOURCE_USERNAME=sa
  - SPRING_DATASOURCE_PASSWORD=""
  - MERCADOPAGO_ACCESS_TOKEN=TEST_ACCESS_TOKEN_DEV

commonLabels:
  environment: development
  version: dev

commonAnnotations:
  environment: development

